version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db 
    image: hamzagul123/vprofiledb
    container_name: vprodb 
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  vproapp:
    build:
      context: ./Docker-files/app 
    image: hamzagul123/vprofileapp_01
    container_name: vproapp 
    ports:
      - "8080:8080"
  vproweb:
    build:
      context: ./Docker-files/web 
    image: hamzagul123/vprofileweb
    container_name: vproapp 
    ports:
      - "80:80"
  
      

